name: Create Release from Artifacts

on:
  push:
    tags:
      - 'v*'

jobs:
  download-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Grab Windows Build
      uses: actions/download-artifact@v4
      with:
        name: cqsaveeditor-windows
        path: ./artifacts

    - name: Grab Linux Build
      uses: actions/download-artifact@v4
      with:
        name: cqsaveeditor-linux
        path: ./artifacts

    - name: Rename Artifacts
      run: |
        mv ./artifacts/cqsaveeditor.exe ./artifacts/windows-cqsaveeditor.exe || echo "Windows binary not found"
        mv ./artifacts/cqsaveeditor ./artifacts/linux-cqsaveeditor || echo "Linux binary not found"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: CQ Save Editor v1.0.${{ github.run_number }}
        files: |
          artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}